// Pass the locally installed playwright-core module as the first argument.
const { chromium } = require(process.argv[2]);
const fs=require('node:fs'),path=require('node:path');
const dir=path.join(__dirname,'artifacts');
let activePage,activeBrowser;const errors=[];
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 activePage=page;activeBrowser=browser;const checks=[];page.on('pageerror',e=>errors.push(String(e)));
 const base=process.env.PLATFORM_URL||'http://127.0.0.1:8772';
 const source=async()=>{await page.goto(base);await page.getByRole('button',{name:'Create your own dataset',exact:true}).waitFor();};
 const generate=async()=>{await page.getByRole('button',{name:'Generate dataset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Evidence report')||document.querySelector('main')?.textContent.includes('The engine failed')||document.querySelector('main')?.textContent.includes('Rejected before generation')||document.querySelector('main')?.textContent.includes('Status unavailable'),{},{timeout:60000});if(!await page.getByRole('heading',{name:'Evidence report',exact:true}).isVisible()){await page.screenshot({path:path.join(dir,'failure.png'),fullPage:true});throw Error(await page.locator('main').innerText());}};
 await source();await page.screenshot({path:path.join(dir,'source.png'),fullPage:true});
 await page.getByRole('button',{name:'Create your own dataset',exact:true}).click();
 await page.getByRole('button',{name:'Edit tables, columns and relationships',exact:true}).click();
 await page.getByRole('button',{name:'Add column to records',exact:true}).click();
 await page.getByRole('textbox',{name:'Table 1 column 2 name',exact:true}).fill('amount');
 if(!await page.getByRole('button',{name:'Generate dataset',exact:true}).isDisabled())throw Error('Unsaved edits did not block generation');
 await page.getByRole('button',{name:'Apply and validate changes',exact:true}).click();
 await generate();checks.push('Guided creation, unsaved-state gate, numeric field and generation');
 await page.getByRole('button',{name:'Start another dataset',exact:true}).click();
 await page.locator('button.example-card[data-example="retail_relational"]').click();
 await generate();await page.getByRole('button',{name:/order_lines \(/}).click();
 const csvLink=page.getByRole('link',{name:'Download CSV',exact:true});
 const csv=await page.request.get(new URL(await csvLink.getAttribute('href'),base).href);if(csv.status()!==200||!(await csv.text()).includes('line_total'))throw Error('CSV download failed');
 await page.screenshot({path:path.join(dir,'retail-report.png'),fullPage:true});checks.push('Retail relational generation, report tabs, CSV download');
 await source();await page.getByRole('button',{name:'Create your own dataset',exact:true}).click();await page.getByRole('button',{name:'Edit tables, columns and relationships',exact:true}).click();await page.getByRole('button',{name:'Advanced JSON',exact:true}).click();
 await page.locator('textarea.json-editor').fill('{broken');await page.getByRole('button',{name:'Apply and validate changes',exact:true}).click();await page.getByText('Check these details',{exact:true}).waitFor();checks.push('Invalid JSON shows a recoverable editor error');
 await source();
 await page.getByLabel('Import specification JSON',{exact:true}).setInputFiles(path.resolve(__dirname,'../../backend/specs/education_relational.json'));
 await generate();checks.push('Education JSON import and generation');
 await source();const lines=['timestamp,value'];for(let i=0;i<120;i++)lines.push(`${new Date(Date.UTC(2026,0,1,i)).toISOString()},${(i*37)%101}`);
 await page.locator('input[type=file][accept=".csv,.tsv,.txt"]').setInputFiles({name:'fixture.csv',mimeType:'text/csv',buffer:Buffer.from(lines.join('\n'))});
 await page.getByRole('button',{name:'Apply suggested fix',exact:true}).waitFor();await page.getByRole('button',{name:'Apply suggested fix',exact:true}).click();
 await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Generate dataset'&&!b.disabled));await generate();checks.push('Timestamp rewrite and ARF generation with a column named value');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(dir,'mobile-report.png'),fullPage:true});
 const size=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth}));if(size.width>size.viewport)throw Error('Mobile page overflows');checks.push('Mobile viewport has no page-wide horizontal overflow');
 await page.keyboard.press('Tab');
 fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({checks,errors,size},null,2));
 if(errors.length)throw Error(errors.join('\n'));
 console.log(JSON.stringify({checks,errors,size}));await browser.close();
})().catch(async e=>{console.error(e);console.error('Page errors:',errors);if(activePage){const text=await activePage.locator('body').innerText();fs.writeFileSync(path.join(dir,'last_failure.txt'),text);console.error(text.slice(0,3000));await activePage.screenshot({path:path.join(dir,'failure.png'),fullPage:true});}if(activeBrowser)await activeBrowser.close();process.exit(1)});
